### ISSUE TITLE
Old RestrictionType -> new ParkingRestrictionType

### ISSUE THREAD

**Issue by ahzf** [e-clearing-net/OCHP#12]
I guess the old RestrictionType is now called ParkingRestrictionType, or?
Sadly not all occurrences in the markdown documentation and the XSD had been updated which leads to some inconsistency.

**Comment by mtdern** [comment]
Actually the exact other way around: ParkingRestriction was the old type, RestrictionType is the new one. We simply forgot renaming one occurence and link.
