### ISSUE TITLE
Tariff Restrictions minOccurance of MinEnergy, MaxEnergy, MinPower, MaxPower, MinDuration, MaxDuration

### ISSUE THREAD

**Issue by ahzf** [e-clearing-net/OCHP#13]
In https://github.com/e-clearing-net/OCHP/blob/master/OCHP.md#tariffrestrictiontype-class the cardinality of MinEnergy, MaxEnergy, MinPower, MaxPower, MinDuration, MaxDuration is defined to be optional and I guess this is a useful behavior, but data-types.xsd defines that their minOccurance must be 1.

**Comment by mtdern** [comment]
Thanks for pointing this out, fixed.
