### ISSUE TITLE
Undefined LiveAuthId

### ISSUE THREAD

**Issue by ahzf** [e-clearing-net/OCHP#14]
In https://github.com/e-clearing-net/OCHP/blob/master/OCHP.md#regularhourstype-class the property and type LiveAuthId is mentioned, but not defined anywhere. https://github.com/thenewmotion/ochp-client/blob/master/src/test/scala/com/thenewmotion/ochp/converters/CDRSpec.scala defines it as "wtf" ;)

**Comment by mtdern** [comment]
I hope you meant the CdrInfoType that still mentions the LiveAuthId? Oversight on my part, removed.
