### ISSUE TITLE
Request(Single|Live)RoamingAuthorisation name mismatches...

### ISSUE THREAD

**Issue by ahzf** [e-clearing-net/OCHP#20]
The TOC talks about:

Messages for live authorisation
RequestLiveRoamingAuthorisation.req
RequestLiveRoamingAuthorisation.conf

but the links are broken.

The text talks about:
Messages for single authorisation
RequestSingleRoamingAuthorisation.req
RequestSingleRoamingAuthorisation.conf

The OCHP v1.4 WSDL talks about:
GetSingleRoamingAuthorisationRequest
GetSingleRoamingAuthorisationResponse

What is now the correct naming?

**Comment by mtdern** [comment]
Correct naming is the changed SingleRoamingAuthorisation. Thanks, fixed!
