### ISSUE TITLE
Optional ratings/MaxSocketPower in the CDRInfo: WSDL vs. documentation

### ISSUE THREAD

**Issue by ahzf** [e-clearing-net/OCHP#21]
According to the OCHP v1.4 WSDL's array-types.xsd there might be an optional 'ratings' XML element within a CDRInfo complexType. This is not described in the documentation at https://github.com/e-clearing-net/OCHP/blob/master/OCHP.md#cdrinfo-class 

The other way round there is a "maxSocketPower" field in the documentation of type "float" and the following description "Maximum available power at the socket in kilowatts. Example: "3.7", "11", "22"" which is not in the WSDL.

**Comment by mtdern** [comment]
Fixed, thanks!
