### ISSUE TITLE
PriceComponent / TariffRestriction in TariffElement: Lists or not lists?

### ISSUE THREAD

**Issue by ahzf** [e-clearing-net/OCHP#24]
PriceComponent and TariffRestriction in TariffElement are both lists in the documentation in https://github.com/e-clearing-net/OCHP/blob/master/OCHP.md#tariffrestrictiontype-class but have a cradinality of 1 in the WSDL https://raw.githubusercontent.com/e-clearing-net/OCHP/master/types/data-types.xsd. I guess both should be lists, or?

**Comment by mtdern** [comment]
The WSDL is correct and the documentation is now as well. See the examples: the list of items should be TariffElements while each TariffElement should consist of exactly one PriceComponent with optional Restrictions on each.
