### ISSUE TITLE
OCHPdirect MaxCurrent and OnePhase missing in InformProvider message documentation

### ISSUE THREAD

**Issue by ahzf** [e-clearing-net/OCHP#29]
The ControlEVSE message has the fields MaxCurrent and OnePhase as EVSE configuration parameters, but they are missing in the InformProvider message documentation. In the WSDL they are present.

**Comment by mtdern** [comment]
Fixed, thank you. Last stage of documentation seems to have had some issues. Same with the StateofCharge information (which got thrown out during the process).
