### ISSUE TITLE
Wrong instance length in regular expression for the Contract-ID

### ISSUE THREAD

**Issue by simonschllng** [e-clearing-net/OCHP#4]
In [Regular expression for Contract-ID validation](https://github.com/e-clearing-net/OCHP/blob/master/OCHP.md#regular-expression-for-contract-id-validation) the instance is defined as `[Cc][A-Za-z0-9]{9}`. what should be `[Cc][A-Za-z0-9]{8}` because the _C_ is counted to the instance as well. This is not affecting the WSDL.

**Comment by mtdern** [comment]
At this point it could be argued, that the [Cc] should be removed instead. The eCHS will accept contract-IDs without the C and many partners make use of contract-IDs like that.

**Comment by simonschllng** [comment]
Not so, if you want to stay in line with eMI3: [emi3group.com/documents-links/](http://emi3group.com/documents-links/) → Part 2 Business Objects [.pdf] → 1.2.2.1 eMA ID Syntax

**Comment by mtdern** [comment]
True, my point above is once more system behavior rather than OCHP....
In this case, we should change https://github.com/e-clearing-net/OCHP/blob/master/OCHP.md#contractid-or-evco-id to reflect this as well, as this is currently missing any reference to the ID-Type 'C'.
