### ISSUE TITLE
OCHPdirect: make InformProvider.req directId optional

### ISSUE THREAD

**Issue by mtdern** [e-clearing-net/OCHP#5]
For the advanced use case "Charge Event" a customer is supposed to be informed of the charging process, even if the process was not started through OCHPdirect.
Thus, an OCHPdirect session has to be **established by the CPO** to inform the EMP of the charging process. To this end, the CPO has to be able to send an InformProvider (as it is the only method they can send to an EMP) without a directId and the EMP in turn has to establish this directId for the session.

**Comment by simonschllng** [comment]
The _directId_ is identifying the OCHP_direct_ session in the operator's backend. Thus the usual case is, that the provider calls _SelectEvse_ and receives a new _directId_ (session id) from the operator. He can then use this _directId_ to control the session.
When the user starts a charging process using a RFID token, and the operator wants to enable a OCHP_direct_ session for it, he simply generates a new _directId_ and calls _Informprovider_ **with** that id. From now on the provider can use this _directId_ to control the session, as ever before.

_Vote to close #5_

**Comment by mtdern** [comment]
Yeah, somehow I didn't even think of that possibility. It does not matter who supplies the directID, this way the CPO can make sure it's unique in their system.

_Closed._
